# Generated by Django 3.0.3 on 2020-05-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_csvdoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CsvDoc',
        ),
        migrations.AlterField(
            model_name='festival',
            name='date',
            field=models.DateTimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='megawatts',
            name='datetime',
            field=models.DateTimeField(unique=True),
        ),
    ]
